baseurl: "http://inkwellhouse.com"
exclude: ['node_modules', '_site', 'app']
markdown: kramdown
navigation:
- text: Home
  url: /
  title: Homepage
- text: About Inkwell House
  url: /about/
  title: About Inkwell House
- text: Contact Us
  url: /contact/
  title: Contact us
sociallinks:
- text: facebook
  url: https://www.facebook.com/jesseasutherland
  icon-class: uniF082