baseurl: "http://youngelpaso.github.io/jesse-website"
exclude: ['node_modules', '_site', 'app']
navigation:
- text: Home
  url: /
  title: Homepage
- text: About
  url: /about/
  title: About this site
- text: Contact
  url: /contact/
  title: Contact me
sociallinks:
- text: google+
  url: https://www.google.com/+JesseSutherland
  icon-class: uniF0D4
- text: linkedin
  url: https://www.linkedin.com/in/jessesutherland
  icon-class: uniF08C
- text: facebook
  url: https://www.facebook.com/jesseasutherland
  icon-class: uniF082
- text: github
  url: https://github.com/youngelpaso
  icon-class: uniF09B
