baseurl: ''
exclude: ['node_modules', '_site', 'app']
navigation:
- text: Home
  url: /
  title: Homepage
- text: About
  url: /about/
  title: About this site
- text: Contact
  url: /contact/
  title: Contact me
