baseurl: "http://inkwellhouse.com"
exclude: ['node_modules', '_site', 'app']
markdown: kramdown
navigation:
- text: Home
  url: /
  title: Homepage
- text: About Inkwell House
  url: /about/
  title: About Inkwell House
- text: Contact Us
  url: /contact/
  title: Contact us
sociallinks:
#- text: facebook
#  url: https://www.facebook.com/joel.d.moran
#  icon-class: uniF082
- text: email
  url: mailto:inkwellhouse@gmail.com
  icon-class: uniF0E0
- text: phone
  url: tel:1-905-524-0150
  icon-class: uniF095